/* jshint indent: 2 */
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('weekDaySlots', {
    centreId:{
    	type:DataTypes.STRING,
    	allownull:false,
    	primaryKey:true,
    	references:{
    		model:'centres',
    		key:'id'
    	}
    },
    dayOfTheWeek:{
    	type:DataTypes.STRING,
    	allownull:false,
    	primaryKey:true,
    	validate:{
	        isIn:[['','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']]
    	}
    },
    shift1Id:{
    	type:DataTypes.STRING,
    	allownull:false,
   		references:{
   			model:'shifts',
   			key:'id'
   		}
    },
    shift2Id:{
    	type:DataTypes.STRING,
    	allownull:false,
   		references:{
   			model:'shifts',
   			key:'id'
   		}
    },
    shift3Id:{
    	type:DataTypes.STRING,
    	allownull:false,
   		references:{
   			model:'shifts',
   			key:'id'
   		}
    },
    shift4Id:{
    	type:DataTypes.STRING,
    	allownull:true,
   		references:{
   			model:'shifts',
   			key:'id'
   		}
    },
    shift5Id:{
    	type:DataTypes.STRING,
    	allownull:true,
   		references:{
   			model:'shifts',
   			key:'id'
   		}
    },
    shift6Id:{
    	type:DataTypes.STRING,
    	allownull:true,
    	references:{
    		model:'shifts',
    		key:'id'
    	}
    }
  }, {
    tableName: 'weekDaySlots'
  });
};
